### ISSUE TITLE
[BUG]He doesn't work with Mythicmobs

### ISSUE THREAD

**Issue by TH2403y** [WolfyScript/WolfyUtils-Spigot#86]
If I remove Mythcimobs, he won't report an error.

[20:35:31] [Server thread/INFO]: TH2403y issued server command: /cc
[20:35:34] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Minecraft: 1.21! Trying to find NMS support
[20:35:34] [Server thread/WARN]: [NBTAPI] [NBTAPI] This Server-Version(1.21-R0.1-SNAPSHOT) is not supported by this NBT-API Version(2.12.4) located in WolfyUtilities. The NBT-API will try to work as good as it can! Some functions may not work!
[20:35:34] [Server thread/INFO]: [NBTAPI] [NBTAPI] Using the plugin 'WolfyUtilities' to create a bStats instance!
[20:35:34] [Server thread/WARN]: [CustomCrafting] Task #7696 for CustomCrafting v4.17-beta.3 generated an exception
java.lang.ExceptionInInitializerError: null
	at wolfyutils-spigot-4.17-beta.5.jar/com.wolfyscript.lib.nbt.nbtapi.NBTItem.convertItemtoNBT(NBTItem.java:340) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/me.wolfyscript.utilities.compatibility.plugins.mythicmobs.MythicMobsStackIdentifier$Parser.from(MythicMobsStackIdentifier.java:96) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/com.wolfyscript.utilities.bukkit.registry.RegistryStackIdentifierParsers.parseIdentifier(RegistryStackIdentifierParsers.java:40) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/com.wolfyscript.utilities.bukkit.registry.RegistryStackIdentifierParsers.parseFrom(RegistryStackIdentifierParsers.java:56) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at customcrafting-spigot-4.17-beta.3.jar/me.wolfyscript.customcrafting.gui.recipe_creator.ButtonRecipeIngredient.lambda$new$1(ButtonRecipeIngredient.java:57) ~[customcrafting-spigot-4.17-beta.3.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/me.wolfyscript.utilities.api.inventory.gui.button.buttons.ActionButton.postExecute(ActionButton.java:145) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/me.wolfyscript.utilities.api.inventory.gui.button.buttons.ItemInputButton.postExecute(ItemInputButton.java:98) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/me.wolfyscript.utilities.api.inventory.gui.GuiUpdate.lambda$postExecuteButtons$0(GuiUpdate.java:216) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at wolfyutils-spigot-4.17-beta.5.jar/me.wolfyscript.utilities.api.inventory.gui.GuiUpdate.postExecuteButtons(GuiUpdate.java:214) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at wolfyutils-spigot-4.17-beta.5.jar/me.wolfyscript.utilities.api.inventory.gui.GuiWindow.lambda$update$0(GuiWindow.java:268) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:91) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1727) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1325) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:81) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.3.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[leaf-1.21.jar:1.21-DEV-1c28bb3]
	at wolfyutils-spigot-4.17-beta.5.jar/com.wolfyscript.lib.nbt.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[wolfyutils-spigot-4.17-beta.5.jar:?]
	... 19 more

**Comment by TH2403y** [comment]
I want not to refund，fix it pls！

**Comment by WolfyScript** [comment]
I'll fix this with the next WolfyUtils update. There are few other bug fixes I need to include in that update. I try to have an update out by the end of the week

**Comment by TH2403y** [comment]
thank you！
